version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
    timezone: America/Mexico_City
  open-pull-requests-limit: 1000
  ignore:
  - dependency-name: angular
    versions:
    - ">= 0"
  - dependency-name: jquery
    versions:
    - ">= 0"
  - dependency-name: mime-db
    versions:
    - "^1.35.0"
  - dependency-name: proxyquire
    versions:
    - "^2.0.0"
  - dependency-name: "@types/node"
    versions:
    - "^10.12.18"
  - dependency-name: typed-css-modules
    versions:
    - 0.6.5
    - 0.6.6
    - 0.6.7
  - dependency-name: fork-ts-checker-webpack-plugin
    versions:
    - 6.0.2
    - 6.1.0
    - 6.1.1
    - 6.2.0
    - 6.2.1
  - dependency-name: "@microsoft/applicationinsights-web-basic"
    versions:
    - 2.5.11
    - 2.6.0
    - 2.6.1
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: ajv
    versions:
    - 6.12.6
    - 7.2.1
    - 7.2.3
    - 8.0.1
    - 8.0.5
  - dependency-name: css-select
    versions:
    - 3.1.0
    - 3.1.2
    - 4.0.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.28
    - 14.14.37
  - dependency-name: "@types/jsdom"
    versions:
    - 16.2.4
    - 16.2.6
    - 16.2.7
  - dependency-name: "@types/lodash"
    versions:
    - 4.14.161
  - dependency-name: eslint-plugin-import
    versions:
    - 2.22.0
  - dependency-name: amphtml-validator
    versions:
    - 1.0.33
  - dependency-name: ora
    versions:
    - 5.0.0
    - 5.3.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: "@octokit/rest"
    versions:
    - 18.0.12
    - 18.1.1
    - 18.2.0
    - 18.3.5
  - dependency-name: log-symbols
    versions:
    - 4.1.0
  - dependency-name: rxjs
    versions:
    - 6.6.6
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.1.3
    - 5.2.0
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
  - dependency-name: postcss
    versions:
    - 8.1.2
    - 8.2.6
    - 8.2.8
  - dependency-name: ts-loader
    versions:
    - 8.0.12
    - 8.0.17
    - 8.0.18
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.2.3
  - dependency-name: globby
    versions:
    - 11.0.2
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.2
    - 17.0.3
  - dependency-name: boxen
    versions:
    - 5.0.0
  - dependency-name: cloudinary
    versions:
    - 1.23.0
    - 1.25.0
  - dependency-name: image-size
    versions:
    - 0.9.1
    - 0.9.4
  - dependency-name: semver
    versions:
    - 7.3.4
  - dependency-name: "@types/sinon"
    versions:
    - 9.0.10
    - 9.0.11
    - 9.0.8
  - dependency-name: "@types/chrome"
    versions:
    - 0.0.127
    - 0.0.133
  - dependency-name: "@types/fs-extra"
    versions:
    - 9.0.6
    - 9.0.8
  - dependency-name: "@types/estree"
    versions:
    - 0.0.46
  - dependency-name: whatwg-fetch
    versions:
    - 3.5.0
    - 3.6.1
  - dependency-name: color-string
    versions:
    - 1.5.4
  - dependency-name: file-type
    versions:
    - 16.0.1
    - 16.2.0
  - dependency-name: puppeteer-core
    versions:
    - 5.5.0
    - 7.1.0
  - dependency-name: "@types/yargs"
    versions:
    - 15.0.12
    - 16.0.0
  - dependency-name: "@types/webpack"
    versions:
    - 4.41.25
    - 4.41.26
  - dependency-name: browserslist
    versions:
    - 4.14.5
    - 4.16.3
  - dependency-name: p-retry
    versions:
    - 4.4.0
  - dependency-name: chrome-remote-interface
    versions:
    - 0.29.0
  - dependency-name: jsdom
    versions:
    - 16.4.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: web-ext
    versions:
    - 5.5.0
  - dependency-name: "@types/express"
    versions:
    - 4.17.9
  - dependency-name: is-svg
    versions:
    - 4.2.1
  - dependency-name: "@types/async"
    versions:
    - 3.2.5
  - dependency-name: sinon
    versions:
    - 9.2.2
  - dependency-name: exceljs
    versions:
    - 4.2.0
  - dependency-name: chokidar
    versions:
    - 3.4.3
  - dependency-name: axe-core
    versions:
    - 4.1.1
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: applicationinsights
    versions:
    - 1.8.8
  - dependency-name: "@types/ejs"
    versions:
    - 3.0.5
  - dependency-name: yargs
    versions:
    - 16.1.1
  - dependency-name: webpack
    versions:
    - 5.4.0
  - dependency-name: markdownlint
    versions:
    - 0.21.1
  - dependency-name: react-dom
    versions:
    - 17.0.1
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: react-syntax-highlighter
    versions:
    - 15.2.1
  - dependency-name: ejs
    versions:
    - 3.1.5
  - dependency-name: acorn-walk
    versions:
    - 8.0.0
